version: '3'

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: node_js_web_app
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/:/web_app
  